insert into anime(id, name, description, photo, number_of_episodes, number_of_seasons, genre) values (1, "Berserk", "Anime que se passa na Era medieval.", "not", 70, 3, "terror");
insert into anime(id, name, description, photo, number_of_episodes, number_of_seasons, genre) values (2, "Naruto", "Anime de lutas ninjas.", "not", 720, 30, "luta");
insert into anime(id, name, description, photo, number_of_episodes, number_of_seasons, genre) values (3, "Kabaneri", "Anime de zumbis.", "not", 12, 1, "aventura");
insert into anime(id, name, description, photo, number_of_episodes, number_of_seasons, genre) values (4, "Digimon", "Anime sobre criaturas digitais que vão para a Terra.", "not", 51, 1, "aventura");
insert into anime(id, name, description, photo, number_of_episodes, number_of_seasons, genre) values (5, "Cavaleiro do Zodíaco", "Anime sobre mitologia e lutas.", "not", 120, 5, "luta");

insert into anime_character(id, anime_id, name, description, favorite_food, photo, height, weight, age) values (1, 1, "Guts", "Guerreiro que carrega uma enorme espada em busca de vingança.", "not", "not", 1.90, 90.0, 30);
insert into anime_character(id, anime_id, name, description, favorite_food, photo, height, weight, age) values (2, 2, "Rock Lee", "Um ninja que nasceu sem habilidades para usar ninjutsu ou genjutsu e que busca mostrar seu valor apenas com taijutsu.", "not", "not", 1.70, 65.0, 18);
insert into anime_character(id, anime_id, name, description, favorite_food, photo, height, weight, age) values (3, 3, "Ikoma", "Jovem inventor que foi mordido por um kabane e com sua ânsia por viver acabou se transformando em um kabaneri.", "not", "not", 1.75, 70.0, 20);
insert into anime_character(id, anime_id, name, description, favorite_food, photo, height, weight, age) values (4, 4, "Takato", "Um jovem estudante japonês que ama digimons ao ponto de criar o seu próprio, se tornando assim um domador digimon.", "not", "not", 1.3, 45.0, 10);
insert into anime_character(id, anime_id, name, description, favorite_food, photo, height, weight, age) values (5, 5, "Ikki de Fênix", "Um vilão no início do anime que logo em seguida se tornou em um excelente anti-herói.", "not", "not", 1.79, 65.0, 16);